In [1]:
import numpy as np
ndarray1=np.zeros((2,3,5),dtype='int16')
print(ndarray1)
ndarray2=np.arange(20)
ndarray2.shape=(2,2,5)
print('--------------------')
print(ndarray2)
#数据类型
print('数据类型：')
print('ndarray1数据类型：',ndarray1.dtype)
print('ndarray2数据类型：',ndarray2.dtype)
print('------------------------------------')
print('数组的形状：')
print('ndarray1数组形状：',ndarray1.shape)
print('ndarray2数据形状：',ndarray2.shape)
print('------------------------------------')
print("数组中总的元素个数")
print("ndarray1总的元素个数",ndarray1.size)
print("ndarray2总的元素个数",ndarray2.size)
print('------------------------------------')
print("ndarray1第二个平面第一行的元素：",ndarray1[1,0])
print("ndarray2第一个平面中间列的元素：")
print(ndarray2[0,0:2,2:3])

#请将ndarray1对象，修改形状为：shape(6,5)；
print('------------------------------------')
ndarray1.shape=(6,5)
print('修改后的ndarray1：')
print(ndarray1)
#请将ndarray2对象的第二个平面进行行、列互换输出（转置输出）；

print('------------------------------------')
print("ndarray2对象的第二个平面进行行、列互换输出:")
n_ndarray2=ndarray2[1]
new_ndarray2=np.transpose(n_ndarray2)
print(new_ndarray2)

print('------------------------------------')
#请将ndarray1对象和ndarray2对象在纵向方向进行堆叠后进行输出；
print("ndarray1对象和ndarray2对象在纵向方向进行堆叠后进行输出:")
new_ndarray2=np.resize(ndarray2,(6,5))
print(np.vstack((ndarray1,new_ndarray2)))
#6）请将ndarray2对象的每个元素都取2倍后输出，
print('------------------------------------')

print(ndarray2*2)

#将6)中的输出的结果再沿着z轴排序，输出排序后结果；
print('------------------------------------')
print(np.sort(ndarray2*2,axis=2))
print('------------------------------------')
##请将ndarray2的数据全部取sin()输出；
print(np.sin(ndarray2))

#将7)中的结果取1位小数点，进行输出
print('------------------------------------')
print(np.around(np.sin(ndarray2),decimals=1))

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
--------------------
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
数据类型：
ndarray1数据类型： int16
ndarray2数据类型： int32
------------------------------------
数组的形状：
ndarray1数组形状： (2, 3, 5)
ndarray2数据形状： (2, 2, 5)
------------------------------------
数组中总的元素个数
ndarray1总的元素个数 30
ndarray2总的元素个数 20
------------------------------------
ndarray1第二个平面第一行的元素： [0 0 0 0 0]
ndarray2第一个平面中间列的元素：
[[2]
 [7]]
------------------------------------
修改后的ndarray1：
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
------------------------------------
ndarray2对象的第二个平面进行行、列互换输出:
[[10 15]
 [11 16]
 [12 17]
 [13 18]
 [14 19]]
------------------------------------
ndarray1对象和ndarray2对象在纵向方向进行堆叠后进行输出:
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 1

In [2]:
#求逆矩阵
import numpy as np
x=np.matrix([[1,2,3],[4,5,6],[7,8,0]])
y=np.linalg.inv(x)
print(y)

[[-1.77777778  0.88888889 -0.11111111]
 [ 1.55555556 -0.77777778  0.22222222]
 [-0.11111111  0.22222222 -0.11111111]]


In [5]:
ndarray3=np.full((2,1,5),1)
print(ndarray3)

ndarray4=np.full((6,1),5)
print(ndarray4)
print(ndarray3+ndarray4)
#每个元素与ndarray4相加

[[[1 1 1 1 1]]

 [[1 1 1 1 1]]]
[[5]
 [5]
 [5]
 [5]
 [5]
 [5]]
[[[6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]]

 [[6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]]]
