In [2]:
import numpy as np
data=[6,7,8,9.0]
arr=np.array(data)
arr

array([6., 7., 8., 9.])

In [3]:
import numpy as np
data=[6,7,8,9.0]
arr=np.array(data,dtype='int16')
arr

array([6, 7, 8, 9], dtype=int16)

In [4]:
import numpy as np
data=[[6,7,8,9.0],[6,7,8,9.0]]
arr=np.array(data)
arr

array([[6., 7., 8., 9.],
       [6., 7., 8., 9.]])

In [9]:
import numpy as np
print(np.zeros(5))
print(np.zeros(5,dtype='int16'))
print(np.zeros((2,1)))

x=np.ones((3,3))
print(np.zeros_like(x))

np.empty((2,2))



[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[0.]
 [0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[6., 7.],
       [8., 9.]])

In [8]:
import numpy as np
a=([1,2,3],[4,5,6])
np.empty_like(a)

array([[852,   0, 852],
       [  0,   1, 435]])

In [10]:
import numpy as np
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [13]:
import numpy as np
np.full((3,2),[1,2])

array([[1, 2],
       [1, 2],
       [1, 2]])

In [14]:
import numpy as np
np.eye(2,dtype='int16')

array([[1, 0],
       [0, 1]], dtype=int16)

In [15]:
import numpy as np
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [16]:
import numpy as np
np.eye(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [17]:
import numpy as np
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
import numpy as np
print(np.arange(3))
print(np.arange(3.0))
print(np.arange(3,7))
print(np.arange(10,1,-2))

[0 1 2]
[0. 1. 2.]
[3 4 5 6]
[10  8  6  4  2]


In [19]:
import numpy as np
list_1=[1,2]
list_2=np.asarray(list_1)
print(list_1,list_2,sep='\n')

[1, 2]
[1 2]


In [20]:
import numpy as np
arr=np.array([1,2])
arr_2=np.asarray(arr)
print(arr,arr_2,sep='\n')

[1 2]
[1 2]


In [22]:
list_1=[1,2]
arr_array=np.array(list_1)
arr_asarray=np.asarray(list_1)
print(arr_array is arr_asarray,arr_array is list_1,arr_asarray is list_1)

arrr=np.array([1,2])
arrr_array=np.array(arr)
arr_asarray=np.asarray(arr)

print(arr_array is arr)
print(arr_asarray is arr)

arr=np.arrray([1,2])

False False False
False
True


In [5]:
import numpy as np
list_1=[1,2]
arr_array=np.array(list_1)
arr_asarray=np.asarray(list_1)
print(arr_array is arr_asarray,arr_array is list_1,arr_asarray is list_1)

arr=np.array([1,2])
arr_array=np.array(arr)
arr_asarray=np.asarray(arr)

False False False


In [7]:
arr=np.array([1,2])
arr_array=np.array(arr)
arr_asarray=np.asarray(arr)

print(arr_array is arr)
print(arr_asarray is arr)

False
True


In [8]:
arr=np.array([1,2])
arr_asarray=np.asarray(arr,'float64')
print(arr,arr_asarray,arr_asarray is arr,sep='\n')


[1 2]
[1. 2.]
False


In [12]:
add_nd=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])
print('shape:',add_nd.shape)
print('size:',add_nd.size)
print('ndim:',add_nd.ndim)
print('itemsize',add_nd.itemsize)
print('dtype:',add_nd.dtype)

shape: (2, 3, 3)
size: 18
ndim: 3
itemsize 4
dtype: int32


In [13]:
arr=np.array([1,2,3,4,5],dtype='int64')
arr.dtype

dtype('int64')

In [14]:
float_arr=arr.astype('float64')
float_arr.dtype

dtype('float64')

In [15]:
arr=np.array([3.7,6.4,2.5])
print(arr)

int_arr=arr.astype('int32')
print(int_arr)

[3.7 6.4 2.5]
[3 6 2]


In [16]:
string_arr=np.array(['2','5.5','3.3'])
int_arr=string_arr.astype('float64')
print(string_arr,int_arr,sep='\n')

['2' '5.5' '3.3']
[2.  5.5 3.3]


In [17]:
arr=np.arange(10)

print(arr)
print(arr[0],arr[3])
print(arr[1:3])
print(arr[1:8:2])
print(arr[1:])

[0 1 2 3 4 5 6 7 8 9]
0 3
[1 2]
[1 3 5 7]
[1 2 3 4 5 6 7 8 9]


In [18]:
arr_2d=np.array([[1,2,3,11],[4,5,6,22],[7,8,9,33],[10,11,12,44]])
print(arr_2d)

print(arr_2d[0][0])
print(arr_2d[0,0])
print(arr_2d[0])
print(arr_2d[0:2,2:4])
print(arr_2d[:2,2:])

[[ 1  2  3 11]
 [ 4  5  6 22]
 [ 7  8  9 33]
 [10 11 12 44]]
1
1
[ 1  2  3 11]
[[ 3 11]
 [ 6 22]]
[[ 3 11]
 [ 6 22]]


In [19]:
add_nd=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])

print(add_nd[0])
print(add_nd[0,0])
print(add_nd[1,0])

print(add_nd[1,0,0])
print(add_nd[1,1:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[11 22 33]
11
[[55 66]
 [88 99]]


In [20]:
add_nd=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])

add_nd[1,0,0]=111
print(add_nd,end='\n******************\n')

add_nd[1,1:,1:]=555
print(add_nd,end='\n******************\n')

add_nd[1,1:,1:]=[1,2]
print(add_nd,end='\n******************\n')

add_nd[1,1:,1:]=[[1,2],[3,4]]
print(add_nd)

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[111  22  33]
  [ 44  55  66]
  [ 77  88  99]]]
******************
[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[111  22  33]
  [ 44 555 555]
  [ 77 555 555]]]
******************
[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[111  22  33]
  [ 44   1   2]
  [ 77   1   2]]]
******************
[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[111  22  33]
  [ 44   1   2]
  [ 77   3   4]]]


In [21]:
add_nd=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])

new_arr=add_nd[1,1:,1:]
print(new_arr,end='\n******************\n')

new_arr[:]=55
print(new_arr,end='\n******************\n')
print(add_nd)

[[55 66]
 [88 99]]
******************
[[55 55]
 [55 55]]
******************
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 55]
  [77 55 55]]]


In [22]:
add_nd=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])
print('===========拷贝的方法==========')
new_arr=add_nd[1,1:,1:].copy()
new_arr[:]=55
print(new_arr,end='\n******************\n')
print(add_nd)

===========拷贝的方法==========
[[55 55]
 [55 55]]
******************
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]


In [23]:
add_nd=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])
print('shape:',add_nd.shape)

print('通过修改ndarray.shpe新数组:')
add_nd.shape=(3,6)
print(add_nd)

shape: (2, 3, 3)
通过修改ndarray.shpe新数组:
[[ 1  2  3  4  5  6]
 [ 7  8  9 11 22 33]
 [44 55 66 77 88 99]]


In [24]:
add_nd=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])

new_arr=add_nd.reshape(6,3)
print('ndarray.reshape方法生成的新数组：')
print(new_arr)
print('ndarray.reshape方法不改变原来的数组：')
print(add_nd)

new_arr1=np.reshape(add_nd,(6,3))
print('ndarray.reshape方法生成的新数组：')
print(new_arr1)
print('ndarray.reshape方法不改变原来的数组：')
print(add_nd)

ndarray.reshape方法生成的新数组：
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 33]
 [44 55 66]
 [77 88 99]]
ndarray.reshape方法不改变原来的数组：
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]
ndarray.reshape方法生成的新数组：
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 33]
 [44 55 66]
 [77 88 99]]
ndarray.reshape方法不改变原来的数组：
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]


In [25]:
add_nd=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])

add_nd.resize(2,6,5)
print('ndarray.resize方法改变原来的数组，不生成新的数组')
print(add_nd)

add_nd=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])

new_add=np.resize(add_nd,(2,6,5))
print('np.resize方法生成的新数组：')
print(new_arr1)
print('np.resize方法不改变原来的数组：')
print(add_nd)

ndarray.resize方法改变原来的数组，不生成新的数组
[[[ 1  2  3  4  5]
  [ 6  7  8  9 11]
  [22 33 44 55 66]
  [77 88 99  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]

 [[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]]
np.resize方法生成的新数组：
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 33]
 [44 55 66]
 [77 88 99]]
np.resize方法不改变原来的数组：
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]


In [26]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
new_add=np.transpose(arr_2d)

print(arr_2d.shape,new_add.shape)
print(new_add is arr_2d,arr_2d,new_add,sep='\n***********************\n')

(4, 3) (3, 4)
False
***********************
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
***********************
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [27]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
new_add=arr_2d.T

print(arr_2d.shape,new_add.shape)
print(new_add is arr_2d,arr_2d,new_add,sep='\n***********************\n')

(4, 3) (3, 4)
False
***********************
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
***********************
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [28]:
arr_2d=np.array([[[[1,2,3],[4,5,6],[1,2,3],[4,5,6]],[[7,8,9],[10,11,12],[1,2,3],[4,5,6]]],[[[1,2,3],[4,5,6],[1,2,3],[4,5,6]],[[7,8,9],[10,11,12],[1,2,3],[4,5,6]]]])
new_add=np.transpose(arr_2d)

print(arr_2d.shape,new_add.shape)
print(new_add is arr_2d)

(2, 2, 4, 3) (3, 4, 2, 2)
False


In [29]:
arr_2d=np.array([[[[1,2,3],[4,5,6],[1,2,3],[4,5,6]],[[7,8,9],[10,11,12],[1,2,3],[4,5,6]]],[[[1,2,3],[4,5,6],[1,2,3],[4,5,6]],[[7,8,9],[10,11,12],[1,2,3],[4,5,6]]]])
new_add=arr_2d.T

print(arr_2d.shape,new_add.shape)
print(new_add is arr_2d)

(2, 2, 4, 3) (3, 4, 2, 2)
False


In [30]:
add_nd1=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])
add_nd2=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,22,33],[44,55,66],[77,88,99]]])

axis_0=np.concatenate((add_nd1,add_nd1))
print(axis_0.shape)
axis_1=np.concatenate((add_nd1,add_nd1),axis=1)
print(axis_1.shape)
axis_2=np.concatenate((add_nd1,add_nd1),axis=2)
print(axis_2.shape)

(4, 3, 3)
(2, 6, 3)
(2, 3, 6)


In [31]:
arr3=np.array([[1],[2],[3]])
arr4=np.array([[4],[5],[6]])
print(arr3.shape,arr4.shape)

print(np.hstack((arr3,arr4)))
print(np.vstack((arr3,arr4)))

(3, 1) (3, 1)
[[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [32]:
x=np.array((1,2,3,4,5))
print(x)

print(x+2)
print(x*2)
print(x/2)
print(x**2)

[1 2 3 4 5]
[3 4 5 6 7]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]


In [33]:
x=np.array((1,2,3,4,5))
y=np.array((2,3,4,5,6))

print(x+y)
print(x*y)
print(x/y)
print(x**y)

[ 3  5  7  9 11]
[ 2  6 12 20 30]
[0.5        0.66666667 0.75       0.8        0.83333333]
[    1     8    81  1024 15625]


In [34]:
x=np.array(((1,),(2,),(3,),(4,)))
y=np.array((((1,2,3,4,5),),((1,2,3,4,5),)))
print(x,y,sep='\n**********************\n',end='\n**********************\n')
print(x.shape,y.shape,end='\n**********************\n')
print(x+y)

[[1]
 [2]
 [3]
 [4]]
**********************
[[[1 2 3 4 5]]

 [[1 2 3 4 5]]]
**********************
(4, 1) (2, 1, 5)
**********************
[[[2 3 4 5 6]
  [3 4 5 6 7]
  [4 5 6 7 8]
  [5 6 7 8 9]]

 [[2 3 4 5 6]
  [3 4 5 6 7]
  [4 5 6 7 8]
  [5 6 7 8 9]]]


In [36]:
x_re=np.arange(4)
x=x_re.reshape(4,1)
print(x)

y=np.arange(5)
print(y)

print(x+y)


[[0]
 [1]
 [2]
 [3]]
[0 1 2 3 4]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [37]:
x=np.arange(8)
print(np.append(x,8))
print(np.append(x,[[3,4],[8,7]]))

x=np.arange(8).reshape(2,4)
print(x)
print(np.append(x,[[3,4],[8,7]]))

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 3 4 8 7]
[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7 3 4 8 7]


In [38]:
x=np.zeros((1,8))
y=np.ones((3,8))
print(x,y,sep='\n')
new_nd=np.append(x,y,axis=0)
print(new_nd.shape,new_nd)

[[0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
(4, 8) [[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [39]:
x=np.zeros((8,3))
y=np.ones((8,4))
print(x,y,sep='\n')
new_nd=np.append(x,y,axis=1)
print(new_nd.shape,new_nd)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(8, 7) [[0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]]


In [40]:
arr_sort=np.arange(40,0,-1).reshape(4,2,5)
print(arr_sort)

print(np.sort(arr_sort,axis=0))

print(np.sort(arr_sort,axis=1))

print(np.sort(arr_sort,axis=2))

arr_sort=np.arange(40,0,-1).reshape(4,2,5)
print(arr_sort)

print(np.sort(arr_sort,axis=2))

print(np.sort(arr_sort))

[[[40 39 38 37 36]
  [35 34 33 32 31]]

 [[30 29 28 27 26]
  [25 24 23 22 21]]

 [[20 19 18 17 16]
  [15 14 13 12 11]]

 [[10  9  8  7  6]
  [ 5  4  3  2  1]]]
[[[10  9  8  7  6]
  [ 5  4  3  2  1]]

 [[20 19 18 17 16]
  [15 14 13 12 11]]

 [[30 29 28 27 26]
  [25 24 23 22 21]]

 [[40 39 38 37 36]
  [35 34 33 32 31]]]
[[[35 34 33 32 31]
  [40 39 38 37 36]]

 [[25 24 23 22 21]
  [30 29 28 27 26]]

 [[15 14 13 12 11]
  [20 19 18 17 16]]

 [[ 5  4  3  2  1]
  [10  9  8  7  6]]]
[[[36 37 38 39 40]
  [31 32 33 34 35]]

 [[26 27 28 29 30]
  [21 22 23 24 25]]

 [[16 17 18 19 20]
  [11 12 13 14 15]]

 [[ 6  7  8  9 10]
  [ 1  2  3  4  5]]]
[[[40 39 38 37 36]
  [35 34 33 32 31]]

 [[30 29 28 27 26]
  [25 24 23 22 21]]

 [[20 19 18 17 16]
  [15 14 13 12 11]]

 [[10  9  8  7  6]
  [ 5  4  3  2  1]]]
[[[36 37 38 39 40]
  [31 32 33 34 35]]

 [[26 27 28 29 30]
  [21 22 23 24 25]]

 [[16 17 18 19 20]
  [11 12 13 14 15]]

 [[ 6  7  8  9 10]
  [ 1  2  3  4  5]]]
[[[36 37 38 39 40]
  [31 32 33 34 35]]



In [41]:
a=np.array([[1,3,7,5],[2,6,4,8]])
print(a)
print('=====================')
print(np.argsort(a))
print('=====================')
print(np.argsort(a,axis=0))
print('=====================')
print(np.argsort(a,axis=1))

[[1 3 7 5]
 [2 6 4 8]]
[[0 1 3 2]
 [0 2 1 3]]
[[0 0 1 0]
 [1 1 0 1]]
[[0 1 3 2]
 [0 2 1 3]]


In [42]:
one_dim_array = np.array([1, 4, 5, 3, 7, 2, 6])
print(np.argmax(one_dim_array))

two_dim_array = np.array([[1, 3, 5], [9, 4, 3]])
print(two_dim_array)
max_index_axis4 = np.argmax(two_dim_array)
max_index_axis0 = np.argmax(two_dim_array, axis = 0)
max_index_axis1 = np. argmax(two_dim_array, axis = 1)
print('若轴不指定: ',max_index_axis4)
print('axis = 0: ',max_index_axis0)
print('axis = 1: ',max_index_axis1)

4
[[1 3 5]
 [9 4 3]]
若轴不指定:  3
axis = 0:  [1 1 0]
axis = 1:  [2 0]


In [43]:
x = np.arange(0, 100, 20)
print(x)
print(np.sin(x))

x = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
print(x)

[ 0 20 40 60 80]
[ 0.          0.91294525  0.74511316 -0.30481062 -0.99388865]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
a = np.array([1.0,5.55, 123, 0.567, 25.562])
print ('原数组：')
print(a)
print('舍入后：')
print('舍入位为默认值：',np.around(a))
print('舍入位为1：',np.around(a,decimals = 1))
print('舍入位为-1：',np.around(a,decimals = -1))

原数组：
[  1.      5.55  123.      0.567  25.562]
舍入后：
舍入位为默认值： [  1.   6. 123.   1.  26.]
舍入位为1： [  1.    5.6 123.    0.6  25.6]
舍入位为-1： [  0.  10. 120.   0.  30.]


In [45]:
x = np.array((1,2,3))
y = np.array((4,5,6))
print(np.dot(x,y))
print(x.dot(y))
print(sum(x*y))

32
32
32
